FROM python:3.13

WORKDIR /app


RUN apt-get update && pip install poetry

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \ && poetry install --no-root

COPY . .

CMD ["bash", "service/shs/works.sh"]
