# Generated by Django 5.1.6 on 2025-03-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='img_path',
        ),
    ]
